name: dating
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  flutter_swipe_button: ^2.1.3
  simple_animations: ^5.2.0
  smooth_page_indicator: ^2.0.1
  google_fonts: ^8.0.0
  shimmer: ^3.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  flutter_card_swiper: ^7.2.0
  badges: ^3.1.2
  video_player: ^2.10.1
  chewie: ^1.13.0
  country_code_picker: ^3.4.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  emoji_picker_flutter: ^4.4.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  glassmorphism: ^3.0.0 
  record: ^6.2.0
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  appinio_swiper: ^2.0.0
  google_maps_flutter: ^2.2.3
  image_cropper: ^11.0.0
  photo_view: ^0.15.0
  image: ^4.7.2
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_image_labeling: ^0.14.1
  confetti: ^0.8.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^19.5.0
  custom_refresh_indicator: ^4.0.1
  flutter_native_splash: ^2.4.7
  permission_handler_platform_interface: ^4.3.0
  agora_rtc_engine: ^6.5.3
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# 1. NATIVE SPLASH CONFIGURATION (Add this section)
# This ensures the image shows up the INSTANT the user clicks the app icon
flutter_native_splash:
  color: "#000000"
  image: assets/image/splash_bg.jpeg
  android_12:
    image: assets/image/splash_bg.jpeg
  fullscreen: true

flutter:
  uses-material-design: true

  # 2. UPDATED ASSETS PATH
  assets:
    - assets/videos/
    - assets/image/ # Changed from 'image' to 'images' to match standard naming